management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: prometheus

spring:
  application:
    name: gateway
  zipkin:
    base-url: http://localhost:9411
    sender:
      type: web
  cloud:
    gateway:
      routes:
        - id: path_route
          uri: http://127.0.0.1:8082
          predicates:
            - Path=/v1/books
        - id: path_route
          uri: http://127.0.0.1:8082
          predicates:
            - Path=/v1/books/{segment}
        - id: path_route
          uri: http://127.0.0.1:8081
          predicates:
            - Path=/v1/isbns
        - id: rewrite_v1
          uri: http://127.0.0.1:8082
          predicates:
            - Path=/books/{segment}
            - Header=X-API-VERSION, v1
          filters:
            - RewritePath=/books/(?<segment>.*),/v1/books/$\{segment}
        - id: rewrite_v1
          uri: http://127.0.0.1:8082
          predicates:
            - Path=/books
            - Header=X-API-VERSION, v1
          filters:
            - RewritePath=/books,/v1/books
        - id: rewrite_v1
          uri: http://127.0.0.1:8081
          predicates:
            - Path=/isbns
            - Header=X-API-VERSION, v1
          filters:
            - RewritePath=/isbns,/v1/isbns

        - id: default_version_v1
          uri: http://127.0.0.1:8081
          predicates:
            - Path=/isbns
          filters:
            - RewritePath=/isbns,/v1/isbns
              #V2
              # HTTP HEADER VERSIONING
        - id: rewrite_v2
          uri: http://127.0.0.1:8083
          predicates:
            - Path=/books/{segment}
            - Header=X-API-VERSION, v2
          filters:
            - RewritePath=/books/(?<segment>.*),/v2/books/$\{segment}
        - id: rewrite_v2
          uri: http://127.0.0.1:8083
          predicates:
            - Path=/books
            - Header=X-API-VERSION, v2
          filters:
            - RewritePath=/books,/v2/books
        - id: rewrite_v2
          uri: http://127.0.0.1:8081
          predicates:
            - Path=/isbns
            - Header=X-API-VERSION, v2
          filters:
            - RewritePath=/isbns,/v1/isbns
        # HTTP ACCEPT MEDIA TYPE HEADER VERSIONING
        - id: rewrite_accept_v2
          uri: http://127.0.0.1:8083
          predicates:
            - Path=/books
            - Header=accept, application/vnd.api\.v2\+json
          filters:
            - RewritePath=/books,/v2/books
        - id: rewrite_accept_v2
          uri: http://127.0.0.1:8083
          predicates:
            - Path=/books/{segment}
            - Header=accept, application/vnd.api\.v2\+json
          filters:
            - RewritePath=/books/(?<segment>.*),/v2/books/$\{segment}
        - id: rewrite_accept_v2
          uri: http://127.0.0.1:8081
          predicates:
            - Path=/isbns
            - Header=accept, application/vnd.api\.v2\+json
          filters:
            - RewritePath=/isbns,/v1/isbns
        # URI PATH VERSIONING
        - id: path_route
          uri: http://127.0.0.1:8083
          predicates:
            - Path=/v2/books
        - id: path_route
          uri: http://127.0.0.1:8083
          predicates:
            - Path=/v2/books/{segment}
        - id: path_route
          uri: http://127.0.0.1:8081
          predicates:
            - Path=/v2/isbns
          filters:
            - RewritePath=/v2/isbns,/v1/isbns

        - id: path_route
          uri: http://127.0.0.1:8081
          predicates:
            - Path=/v2/isbns
          filters:
            - RewritePath=/v2/isbns,/v1/isbns


# SECURITY CONFIGURATION TO BE APPLIED (remove comments to apply it)
  security:
    oauth2:
      client:
        registration:
          login-client:
            provider: authz
            client-id: gateway
            client-secret: secret3
            authorization-grant-type: client_credentials
            redirect-uri-template: "{baseUrl}/"
            scope: gateway
        provider:
          authz:
            authorization-uri: http://localhost:8009/oauth2/authorize
            token-uri: http://localhost:8009/oauth2/token
            user-info-uri: http://localhost:8009/oauth2/userinfo
            user-name-attribute: sub
            jwk-set-uri: http://localhost:8009/oauth2/token_keys
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8009

